from __future__ import annotations
PATCHES=[("Retrieval ACL enforcement","Retrieval ACL bypass","rag_retrieval"),("Tenant isolation checks","Cross-tenant retrieval leakage","authorization"),("Source provenance validation","Untrusted source grounding","rag_retrieval"),("Permission freshness validation","Stale permission retrieval","authorization"),("Prompt-injection defense in retrieved context","Prompt injection through retrieved documents","rag_retrieval"),("Context construction security","Context poisoning","rag_retrieval"),("Citation integrity checks","Citation/source mismatch","rag_retrieval"),("Answer-source consistency checks","Unsupported answer sourcing","rag_retrieval"),("Tool authorization","Unauthorized tool execution","agent_tool"),("High-risk action approval","High-risk tool action without approval","agent_tool"),("Tool output validation","Untrusted tool output","agent_tool"),("Agent loop prevention","Agent loop/excessive autonomy","agent_tool"),("Agent memory poisoning defense","Agent memory poisoning","agent_tool"),("MCP identity binding","MCP confused-deputy risk","mcp"),("MCP scope validation","MCP cross-tenant exposure","mcp"),("MCP confused-deputy defense","MCP confused-deputy risk","mcp"),("Artifact upload/download security","Artifact secret/PII exposure","artifact_sandbox"),("Secret/PII detection","Secret/PII exposure","artifact_sandbox"),("Sandbox command restriction","Unsafe sandbox command execution","artifact_sandbox"),("Egress/SSRF controls","SSRF/egress abuse","backend"),("Audit event emission","Missing audit trail","audit_telemetry"),("Telemetry metrics","Missing telemetry","audit_telemetry"),("Policy decision enforcement","Missing policy enforcement","policy"),("CI security gates","Missing CI gate","ci_cd"),("Evidence generation","Missing evidence proof","evidence")]
def patch_points(arch: dict) -> list[dict]:
    out=[]
    for name,threat,cat in PATCHES:
        cands=arch.get(cat,[])[:10]
        status="unconfirmed" if cands else "missing"
        out.append({"control_name":name,"threat_addressed":threat,"likely_project_layer":cat,"candidate_files_or_folders":cands,"confidence_level":"medium" if cands else "low","evidence_currently_found":cands or ["I cannot confirm this from the provided project."],"missing_evidence":["negative/security tests","demo attack","CI evidence","runtime/staging evidence"],"implementation_status":status,"evidence_strength_level":1 if cands else 0,"control_maturity_level":1 if cands else 0,"required_tests":[f"test_{cat}_control"],"required_demo_attack":f"demo attack for {threat}","required_audit_event":f"audit.{cat}.{name.lower().replace(' ','_')}","required_telemetry_metric":f"realworldbuilder.{cat}.decision.count","required_evidence_file":f"evidence/{name.lower().replace(' ','_')}.md","safe_public_claim":"A local readiness scan identified patch points and missing evidence; control effectiveness is not proven.","manual_review_marker":["auto_detected" if cands else "needs_manual_review","needs_runtime_test","needs_ci_evidence","needs_staging_evidence","needs_external_validation"]})
    return out
